config/routes.rb
PracticeApp::Application.routes.draw do
  get "users/new"
  root to: 'static_pages#home' 
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/signup', to: 'users#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  
  validates :password, presence: true, length: { minimum: 6 }
  validate :password_confirmation, presence: true 
  before_save {|user| user.email = email.downcase}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

private

  def user_parameters
    params.require(:user).permit(:name, :email)
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = "Practice App by Michael Griffiths"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://instant-inventories.com">Instant Inventories</a>
    by Michael Griffiths
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %><li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://instant-inventories.co.uk/user">Instant Inventories Log-in</a></li>
   </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "practice app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Sign in", signup_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
 </head>
  <body>
   <%= render 'layouts/header' %> 
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>This is a very simple Practice App written using the Rails framework</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Find contact information on this page</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is the help page for Practice App</p>

app/views/static_pages/home.html.erb
<h1>Practice App</h1>
<p>Welcome to the home page for the Practice App</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<p>This is where users can sign up!</p>